### ISSUE TITLE
[Bug]: Possible crash with Terrablender

### ISSUE THREAD

**Issue by Sunconure11** [samedifferent/Ecologics#74] opened 2022-07-16 20:46 UTC
### Mod Version

2.1.4

### Mod Loader

Fabric

### Mod Loader Version

0.17.1-beta 6

### What happened?

Game seems to be crashing, and one of the classes blamed is here. I am on Quilt.

### latest.log

https://pastebin.com/PTbCiuUi

https://pastebin.com/rjT1DDx6

**Comment by samedifferent** [comment] 2022-07-16 20:51
The issue is with SnowyLeavesPlus. I submitted a fix to their GitHub but they never released it into the mod for some reason. Delete SnowyLeavesPlus and it will work.

**Comment by Sunconure11** [comment] 2022-07-16 20:58
Just pulled it... no dice

**Comment by samedifferent** [comment] 2022-07-16 20:59
Can you send the updated logs with snowy leaves plus uninstalled?

**Comment by Sunconure11** [comment] 2022-07-16 21:01
https://pastebin.com/BGxjYBMi

https://pastebin.com/sL5q2gMC

**Comment by samedifferent** [comment] 2022-07-16 21:06
Ecologics is no longer mentioned there. Does removing Ecologics fix the crash? (Also the latest version of Ecologics is 2.1.4 btw which has some QOL improvements and a few minor bug fixes - shouldn't affect this startup issue but I thought I'd let you know anyway)

**Comment by Sunconure11** [comment] 2022-07-16 21:07
Looks like Ecologics didn't fully update from the launcher.

**Comment by Sunconure11** [comment] 2022-07-16 21:08
Will try pulling it, but due to some things coming up, I might not be able to help further

**Comment by Sunconure11** [comment] 2022-07-16 21:13
https://pastebin.com/sL5q2gMC

https://pastebin.com/JXiVdi2a

**Comment by samedifferent** [comment] 2022-07-16 21:17
If removing Ecologics didn't fix it then I think I'll go ahead and close this issue. I'm not really sure what's wrong but it's clearly not this. I would report the issue to Terrablender.

**Closed as completed by samedifferent** 2022-07-16 21:17 UTC
Labels: bug
