### ISSUE TITLE
[Bug]: Crash while placing a sign

### ISSUE THREAD

**Issue by TheButterbrotMan** [samedifferent/Ecologics#30] opened 2022-04-16 02:14 UTC
### Mod Version

1.5.2

### Mod Loader

Fabric

### Mod Loader Version

0.13.3

### What happened?

Crash while placing a sign

### latest.log

https://bytebin.lucko.me/JXZcCWldmh

**Comment by PhoenixVX** [comment] 2022-04-16 02:16
This is a duplicate of #26. As for the reason, I haven't been able to investigate why such a thing has been happening yet in-depth.

**Comment by TheButterbrotMan** [comment] 2022-04-16 02:18
My modpack: https://www.curseforge.com/minecraft/modpacks/deathdusk

**Comment by TheRanker** [comment] 2022-04-16 18:32
https://bytebin.lucko.me/tmcovf0Lim


heres another crash with the sign issue agian....

please fix this.

**Comment by PhoenixVX** [comment] 2022-04-16 19:28
As far as I can see, this isn't supposed to be happening. Considering the way the code is, which is the same as vanilla, it shouldn't be crashing, so I am suspecting a mod compatibility issue. I've tried to launch Deathdusk and succeeded in getting into the world with my crappy PC, but commands nor turning to creative mode worked, so I wasn't able to debug what the issue was from there.

@TheRanker Can you share similar (likely performance) mods between these that are not Sodium nor DashLoader?

**Comment by TheRanker** [comment] 2022-04-16 19:33
I'll see if I can do you one better. I also have the mod in my modpack. And same issue.  If you don't mind as it'll take some time, I'll replicate it in mine and start to isolate mods. Try to get you minimal mod count to replicate.

**Comment by TheButterbrotMan** [comment] 2022-04-16 19:33
> As far as I can see, this isn't supposed to be happening. Considering the way the code is, which is the same as vanilla, it shouldn't be crashing, so I am suspecting a mod compatibility issue. I've tried to launch Deathdusk and succeeded in getting into the world with my crappy PC, but commands nor turning to creative mode worked, so I wasn't able to debug what the issue was from there.
> 
> @TheRanker Can you share similar (likely performance) mods between these that are not Sodium nor DashLoader?

First join can take sometime. Really takes sometime.

I can load a world on FX 6300 lol.

**Comment by PhoenixVX** [comment] 2022-04-16 19:34
Thanks! The issue cannot be reproduced as is right now, unfortunately.
An Intel Core i5-8250U and 12 GB of RAM was literally triggering a thermal paste meltdown.
![image](https://user-images.githubusercontent.com/24632178/163689025-a21e4c1f-5a3d-436e-abea-2d8a55cfcf86.png)

**Comment by TheButterbrotMan** [comment] 2022-04-16 19:38
> Thanks! The issue cannot be reproduced as is right now, unfortunately.
> An Intel Core i5-8250U and 12 GB of RAM was literally triggering a thermal paste meltdown.
> ![image](https://user-images.githubusercontent.com/24632178/163689025-a21e4c1f-5a3d-436e-abea-2d8a55cfcf86.png)
> 

Oh lol.

**Comment by PhoenixVX** [comment] 2022-04-16 19:39
But, hey, when it did run, it had 40 FPS constant!

**Comment by TheButterbrotMan** [comment] 2022-04-16 19:44
I'm having 24 🥲

**Comment by TheRanker** [comment] 2022-04-16 19:50
I got an i7 24gb ram. Not an issue lol 
just takes time to do the testing .

**Comment by PhoenixVX** [comment] 2022-04-16 19:51
Thanks!

**Comment by CityGrump** [comment] 2022-04-18 14:23
Same issue here when placing flowering azalea wall sign on two clients, using Better Minecraft Server Pack V6.5

[crash-2022-04-18_15.04.09-client.txt](https://github.com/samedifferent/Ecologics/files/8506188/crash-2022-04-18_15.04.09-client.txt)
[crash-2022-04-18_15.06.28-client.txt](https://github.com/samedifferent/Ecologics/files/8506189/crash-2022-04-18_15.06.28-client.txt)
.

**Comment by CityGrump** [comment] 2022-04-18 15:05
> 

Found a way save my world from the crashing Flowering Azalea Wall Signs of Doom, by forceloading the chunk with the sign/s (/forceload add -208 336 -192 351 & /forceload add -336 128 -321 143) i used the setblock (/setblock -202 64 377  jungle_trapdoor & /setblock -312 64 133 ) to remove the signs.

You can find the sign location and chunk in the crash log under -- Block Entity Details -- Details:

Just remember to unmark the force loaded chunks after this fix (/forceload remove all).
Hope this helps anyone else whos affected by this bug!!

**Comment by TheRanker** [comment] 2022-04-18 18:49
thats not a fix anyone can do for modpack devs.. this bug needs to be fixed in code.
working on replicating it and trying to isolate the mods causing it.

**Comment by PhoenixVX** [comment] 2022-04-18 20:35
Biome makeover seems to be the conflicting mod.

**Comment by samedifferent** [comment] 2022-04-23 21:24
Fixed: https://www.curseforge.com/minecraft/mc-mods/ecologics/files/3765328

**Closed by samedifferent** 2022-04-23 21:24 UTC
Labels: bug
